### ISSUE TITLE
Hi, I submitted it again just now, and the workers on EvalAI still returned me the same error. Could you please check it again?

### ISSUE THREAD

**Issue by chantsss** [nutonomy/nuscenes-devkit#888] opened 2023-02-21 07:17 UTC
Hi, I submitted it again just now, and the workers on EvalAI still returned me the same error. Could you please check it again?

_Originally posted by @chantsss in https://github.com/nutonomy/nuscenes-devkit/issues/887#issuecomment-1437360738_

**Comment by chantsss** [comment] 2023-02-21 07:25
![image](https://user-images.githubusercontent.com/55359840/220276144-bbfe89c8-5444-4916-9af3-99898445fbed.png)

**Comment by chantsss** [comment] 2023-02-21 07:26
The Stdout file shows:
Starting Evaluation...
Unpacking dataset...
Unpacking user submission...
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 64.692 seconds.
======
Reverse indexing ...
Done reverse indexing in 16.2 seconds.
======

**Comment by chantsss** [comment] 2023-02-21 07:29
The Stderr file shows as following:
![image](https://user-images.githubusercontent.com/55359840/220276996-220ca419-a65a-4d81-ae62-4b020c781d5c.png)

**Comment by whyekit-motional** [comment] 2023-02-22 01:40
Closing this as it is a duplicate of https://github.com/nutonomy/nuscenes-devkit/issues/887

**Closed by whyekit-motional** 2023-02-22 01:40 UTC
