### ISSUE TITLE
kitti data format

### ISSUE THREAD

**Issue by kkrl1111** [nutonomy/nuscenes-devkit#921] opened 2023-05-15 07:39 UTC
Hello, I would like to change the Kitti format to Nuscenes format. Can I do this and how should I do it？

**Comment by whyekit-motional** [comment] 2023-05-15 08:02
Duplicate of https://github.com/nutonomy/nuscenes-devkit/issues/792#issuecomment-1547339402

**Closed by whyekit-motional** 2023-05-15 08:02 UTC
