### ISSUE TITLE
nuScenes's radar data ( vx and vy ) does not point from radar origin to radar point !?

### ISSUE THREAD

**Issue by joeking11829** [nutonomy/nuscenes-devkit#764] opened 2022-05-17 05:56 UTC
Based on the Issue #748 
> @joeking11829 do take a look at the following: https://forum.nuscenes.org/t/radar-vx-vy-and-vx-comp-vy-comp/283
<br>

Hi @whyekit-motional ,

I read the article, but I could not get any conclusion.

In the disscussion, 
the vector compose of "vx" and "vy" must point from radar origin to radar point
[ reference from "isrohutama" ]
![image](https://user-images.githubusercontent.com/5969040/168737033-02609c8f-331f-428d-b9ea-c863acb68084.png)

But it seems to me that nuScenes's radar data ( vx and vy ) does not behave that way.
And it make me confused that how the compensated velocities are compensated by ego motion,
it make the vector compose of "vx_comp" and "vy_comp" point from radar origin to radar point, but the vector compose of "vx" and "vy" does not.

Any ideas ?

Thanks !!

**Comment by whyekit-motional** [comment] 2022-05-18 07:09
Duplicate of #748

**Closed by whyekit-motional** 2022-05-18 07:09 UTC
