### ISSUE TITLE
Dimensions and position of local maps 

### ISSUE THREAD

**Issue by AndreSchakkal** [nutonomy/nuscenes-devkit#926] opened 2023-05-29 17:40 UTC
Thank you for your answer.
I'm now able to get the coordinates (more or less), however I think there's some rotation that's missing in my code. Do you happen to know what's missing?
![download (2)](https://github.com/nutonomy/nuscenes-devkit/assets/126706635/0e14a8e4-01ea-42f2-babf-1f86e9d4237d)

_Originally posted by @AndreSchakkal in https://github.com/nutonomy/nuscenes-devkit/issues/925#issuecomment-1567350614_

**Comment by whyekit-motional** [comment] 2023-05-30 01:37
Duplicate of https://github.com/nutonomy/nuscenes-devkit/issues/925#issuecomment-1567350614

**Closed by whyekit-motional** 2023-05-30 01:37 UTC
