### ISSUE TITLE
Please forgive me for re-opening this problem，I think I didn't explain the problem.

### ISSUE THREAD

**Issue by 304886938** [nutonomy/nuscenes-devkit#743] opened 2022-03-31 01:59 UTC
Maybe I didn't clear the problem，The radar data provided by the Nuscenes is sparse point clouds that has been handled by a CFAR (Constant False Alarm Rate) algorithm. I want to guide whether you can provide the original data that has not been processed with CFAR.
In addition, can we get dense data after transitioning of your method?
Thank you for your answer!

**Comment by whyekit-motional** [comment] 2022-03-31 02:45
Duplicate of #739

**Closed by whyekit-motional** 2022-03-31 02:45 UTC
