### ISSUE TITLE
Tracking evaluation on EvalAI fails without returning any error

### ISSUE THREAD

**Issue by quan-dao** [nutonomy/nuscenes-devkit#546] opened 2021-01-22 11:58 UTC
Hello,
I've been trying to evaluate my tracking result of the Test Set on eval.ai website. Despite the offline evaluation (against the validation set) executes fine, my submission for the Test Set generated using the same code can't be evaluated. The evaluation stops with the following Stdout and no Stderr:
```
Starting Evaluation...
Submission related metadata:
Unpacking dataset...
Unpacking user submission...
Evaluating for test phase
======
Loading NuScenes tables for version v1.0-private-test...
23 category,
8 attribute,
4 visibility,
11997 instance,
12 sensor,
1800 calibrated_sensor,
462901 ego_pose,
15 log,
150 scene,
6008 sample,
462901 sample_data,
201130 sample_annotation,
4 map,
Done loading in 10.3 seconds.
======
Reverse indexing ...
Done reverse indexing in 2.2 seconds.
======
Initializing nuScenes tracking evaluation
Loaded results from /tmp/tmpnlpt04pc/submission/nuscenes_test_megvii.json. Found detections for 6008 samples.
Loading annotations for test split from nuScenes version: v1.0-private-test
Loaded ground truth annotations for 6008 samples.
Filtering tracks
```
To generate my submission, I use the baseline MEGVII detection result and the US split of the test set.
What should I do to get my submission evaluated?

**Comment by holger-nutonomy** [comment] 2021-01-25 01:54
Hi. We are currently evaluating this with the help of the EvalAI admins. We'll let you know of the outcome.

**Comment by holger-nutonomy** [comment] 2021-01-29 05:16
Hi @quan-dao. Just to let you know that the EvalAI admins are still on this. Apparently there was an incompatibility issue between matplotlib and pillow that only occurred for your submission, not for others :-(.

**Comment by quan-dao** [comment] 2021-01-29 08:30
Hi @holger-nutonomy , thank you for spending your time on my issue. If this issue only occurs for my submission, is there anything I can do to correct my submission?

**Comment by whyekit-aptiv** [comment] 2021-01-29 09:26
Hi @quan-dao, we believe it's an issue specific to EvalAI; do sit tight for a bit and we will let you know if any action is required on your part.

**Comment by whyekit-aptiv** [comment] 2021-01-31 03:20
@quan-dao, is there an email address we can contact you via?

**Comment by quan-dao** [comment] 2021-01-31 15:23
Hi @whyekit-aptiv, you reach me at minh-quan.dao@ls2n.fr

**Comment by whyekit-aptiv** [comment] 2021-02-01 13:20
Working with EvalAI on this; closing this issue as it is not directly relevant to the devkit

**Closed by whyekit-aptiv** 2021-02-01 13:20 UTC

**Comment by jialeli1** [comment] 2022-07-18 12:53
I tried to submit the test results of lidarseg and also got an error with no information.
I passed the local file validation using _nuscenes.eval.lidarseg.validate_submission_
How should I fix it?

```
Starting Evaluation...
Submission related metadata:
Unpacking dataset...
Unpacked /tmp/tmpw9zx4i6m/compute/challenge_data/challenge_720/phase_data/phase_1549/bb9bb38a-ea59-4266-8a50-7f2fdc109dac.zip to /tmp/tmp2f23q79t/dataset.
Unpacking user submission...
Unpacked /tmp/tmpw9zx4i6m/compute/submission_files/submission_213616/fea0a3f6-18ad-481a-9d77-9b0e4aa4c95a.zip to /tmp/tmp2f23q79t/submission.
Evaluating for test phase
======
Loading NuScenes tables for version v1.0-test...
Loading nuScenes-lidarseg...
32 category,
8 attribute,
4 visibility,
11997 instance,
12 sensor,
1800 calibrated_sensor,
462901 ego_pose,
15 log,
150 scene,
6008 sample,
462901 sample_data,
201130 sample_annotation,
4 map,
6008 lidarseg,
Done loading in 9.579 seconds.
======
Reverse indexing ...
Done reverse indexing in 2.1 seconds.
======
```

**Comment by whyekit-motional** [comment] 2022-07-18 15:26
@jialeli1 it seems that this is a duplicate of https://github.com/nutonomy/nuscenes-devkit/issues/788
